"""
debug_step5_decoding_averaged.py
---------------------------------
Validates the LDA decoding pipeline with CoSMoMVPA-style trial averaging.

CoSMoMVPA's 'cosmo_average_samples' reduces noise by averaging groups of
n_average trials from the same class into 'super-trials' before classification.
This script replicates that approach and compares the resulting per-bin
decoding accuracies against the MATLAB/CoSMoMVPA ground truth.

Key design decisions
---------------------
- Averaging is applied *inside* each cross-validation fold to prevent data
  leakage: super-trials are built separately for the train and test splits.
- Both train and test sets are averaged (matching CoSMoMVPA's behaviour), which
  reduces noise in the test set and raises accuracy compared to raw-data testing.
- The number of super-trials per class is fixed at 200, approximating the
  volume CoSMoMVPA would produce across ~10 chunks × 20 repeats.
- Classifier: LDA with LSQR solver and automatic Ledoit-Wolf shrinkage,
  preceded by z-score standardisation.
"""

import numpy as np
import scipy.io
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score

# ── CONFIG ────────────────────────────────────────────────────────────────────
mat_features_path = Path("originalCode/debug_step2_features.mat")
mat_results_path  = Path("originalCode/debug_step2b_results.mat")
# ─────────────────────────────────────────────────────────────────────────────


def cosmo_like_averaging(X, y, n_average=4, n_repeats=20, seed=42):
    """
    Replicate CoSMoMVPA's 'cosmo_average_samples' by creating super-trials.

    For each class, 'num_super_trials' super-trials are generated by randomly
    drawing n_average trials (with replacement) and averaging them. This
    approximates CoSMoMVPA's per-chunk, per-repeat averaging scheme.

    Parameters
    ----------
    X           : np.ndarray, shape (n_trials, n_features)
    y           : np.ndarray, shape (n_trials,)
    n_average   : int
        Number of single trials to average into one super-trial.
    n_repeats   : int
        Unused; kept for API compatibility with CoSMoMVPA parameter naming.
    seed        : int
        Random seed for reproducibility.

    Returns
    -------
    X_avg : np.ndarray, shape (n_classes × num_super_trials, n_features)
    y_avg : np.ndarray, shape (n_classes × num_super_trials,)
    """
    rng     = np.random.RandomState(seed)
    classes = np.unique(y)

    X_new = []
    y_new = []

    # Fixed super-trial count per class, approximating CoSMoMVPA's output
    # volume (~10 chunks × 20 repeats = 200 samples per class per label).
    num_super_trials = 200

    for cls in classes:
        cls_indices = np.where(y == cls)[0]

        for _ in range(num_super_trials):
            # Sample with replacement — matches CoSMoMVPA's default behaviour
            # when the pool size is smaller than n_average × n_repeats.
            picks     = rng.choice(cls_indices, size=n_average, replace=True)
            avg_trial = np.mean(X[picks], axis=0)
            X_new.append(avg_trial)
            y_new.append(cls)

    return np.array(X_new), np.array(y_new)


def run_decoding_averaged():
    print("─── START: debug_step5 (LDA DECODING WITH AVERAGING) ───\n")

    # ── 1. Load feature matrix ────────────────────────────────────────────────
    # Expected layout: (n_trials, n_channels, n_bins)
    try:
        mat_in      = scipy.io.loadmat(mat_features_path, squeeze_me=True)
        features    = mat_in['feature_matrix']   # (trials, channels, bins)
        targets_all = mat_in['targets']
    except Exception as e:
        print(f"ERROR – could not load feature matrix: {e}")
        return

    # ── 2. Load MATLAB ground-truth decoding accuracies ───────────────────────
    try:
        mat_res    = scipy.io.loadmat(mat_results_path, squeeze_me=True)
        dec_struct = mat_res['decoding_accuracy']

        # Handle variable struct shapes returned by scipy.io
        if dec_struct.shape in [(1, 4), (4,)]:
            res_self = dec_struct[0]
        else:
            res_self = dec_struct

        gt_acc = np.squeeze(res_self['samples'].item())
    except Exception as e:
        print(f"ERROR – could not load MATLAB results: {e}")
        return

    # ── 3. Prepare data ───────────────────────────────────────────────────────
    # Use only the first target column; drop trials with NaN labels.
    y_full     = targets_all[:, 0]
    valid_mask = ~np.isnan(y_full)
    y_full     = y_full[valid_mask]
    X_full     = features[valid_mask]

    n_bins = X_full.shape[2]
    print(f"  Trials : {X_full.shape[0]}  |  Channels : {X_full.shape[1]}  "
          f"|  Bins : {n_bins}")
    print(f"  Running decoding with CoSMo-style averaging (n_average = 4) ...\n")

    # ── 4. Classifier ─────────────────────────────────────────────────────────
    # LDA with LSQR solver and automatic Ledoit-Wolf shrinkage, preceded by
    # z-score standardisation (zero mean, unit variance per feature).
    clf = make_pipeline(
        StandardScaler(),
        LinearDiscriminantAnalysis(solver='lsqr', shrinkage='auto')
    )

    # ── 5. Per-bin decoding loop ──────────────────────────────────────────────
    py_accuracies = []

    for b in range(n_bins):
        X_bin = X_full[:, :, b]

        # Stratified 10-fold CV on the *raw* trial indices.
        # Averaging is applied inside each fold to prevent data leakage:
        # super-trials in the training set are built independently from those
        # in the test set.
        cv     = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
        scores = []

        for train_idx, test_idx in cv.split(X_bin, y_full):
            X_train_raw, X_test_raw = X_bin[train_idx], X_bin[test_idx]
            y_train_raw, y_test_raw = y_full[train_idx], y_full[test_idx]

            # Build super-trials separately for train and test splits.
            # Different seeds ensure train and test pools are independent.
            X_train_avg, y_train_avg = cosmo_like_averaging(
                X_train_raw, y_train_raw, n_average=4, seed=b
            )
            X_test_avg, y_test_avg = cosmo_like_averaging(
                X_test_raw, y_test_raw, n_average=4, seed=b + 100
            )

            clf.fit(X_train_avg, y_train_avg)
            pred = clf.predict(X_test_avg)
            scores.append(accuracy_score(y_test_avg, pred))

        bin_acc = np.mean(scores)
        py_accuracies.append(bin_acc)

        if b % 5 == 0:
            print(f"  Bin {b:>2} / {n_bins - 1}  —  accuracy = {bin_acc:.3f}")

    py_accuracies = np.array(py_accuracies)

    # ── 6. Summary metrics ────────────────────────────────────────────────────
    correlation = np.corrcoef(gt_acc, py_accuracies)[0, 1]
    rmse        = np.sqrt(np.mean((gt_acc - py_accuracies) ** 2))

    print(f"\n─── RESULTS ────────────────────────────────────")
    print(f"  Correlation (Python vs. MATLAB) : {correlation:.4f}")
    print(f"  RMSE                            : {rmse:.4f}")

    # ── 7. Diagnostic plot ────────────────────────────────────────────────────
    plt.figure(figsize=(10, 6))

    plt.axhline(1 / 3, color='gray', linestyle=':', label='Chance level (1/3)')
    plt.plot(gt_acc,        'r-o',  label='MATLAB (CoSMoMVPA)',
             linewidth=2, alpha=0.7)
    plt.plot(py_accuracies, 'b--x', label=f'Python (averaged,  r = {correlation:.2f})',
             linewidth=2, alpha=0.7)

    plt.title(f"LDA Decoding with Trial Averaging  "
              f"(corr = {correlation:.3f},  RMSE = {rmse:.3f})")
    plt.xlabel("Time bin")
    plt.ylabel("Decoding accuracy")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    out_file = "debug_step5_averaging.png"
    plt.savefig(out_file)
    print(f"\nPlot saved: {out_file}")
    plt.show()


if __name__ == "__main__":
    run_decoding_averaged()
